### ISSUE TITLE
Cursor position should be invariant on :ImportName call

### ISSUE THREAD

**Issue by jan-matejka** [mgedmin/python-imports.vim#8]
Cursor should stay at the same position after :ImportantName is called. Currently, cursor is positioned somewhere in the imports area at the top of the file after :ImportName is called instead.

**Comment by mgedmin** [comment]
This is by design: I want to see where `:ImportName` (mis)placed the import statement.  You can go back to the original line by pressing `''` (or <code>``</code>).

The plugin is very careful and uses `:keepjumps` everywhere so that `''` will go back to the right place.

**Comment by mgedmin** [comment]
Turns out I already have this implemented as an optional feature, if you use `:ImportName!` instead of `:ImportName`, but completely forgot about it.

This feature is older than this git repository.  It's older than the git repository of my ~/.vim/.  It was added when python-imports.vim lived in the Subversion repository of my home directory, and digging through that history is too inconvenient for me right now.
